import type { ExperienceItem } from './types'

export const experience: ExperienceItem[] = [
  {
    id: '1',
    company: 'Enhesa',
    title: 'Senior Software Engineer - Tech Lead',
    startDate: '2023-03',
    location: 'Lisbon, Portugal',
    description: [
      'Maintenance, design, and development of core microservices: Identity Service, User Management, Export Service, Document Service, Home Page',
      'Resolved a major performance bottleneck in Identity Service (/connect/token): reduced average latency from ~1.5s to <100ms (~93% improvement) by redesigning flow, adding distributed cache (Redis) with TTL aligned to token expiration, and adding a circuit breaker to improve resilience and scalability',
      'Designed and delivered an Integrations Service enabling configuration-driven integrations without code changes; reduced integration setup time from weeks to hours/days',
      'Led a cross-service initiative reducing production vulnerabilities to zero',
      'Migrated CI/CD pipelines from GoCD to Azure DevOps Pipelines to standardize and automate deployments',
    ],
    technologies: [
      'C# .NET 10',
      'Kafka',
      'Elasticsearch',
      'PostgreSQL',
      'Entity Framework',
      'Kubernetes',
      'Redis',
    ],
  },
  {
    id: '2',
    company: 'Enhesa',
    title: 'Software Engineer',
    startDate: '2022-05',
    endDate: '2023-05',
    location: 'Lisbon, Portugal',
    description: [
      'Developed and maintained backend services for the Enhesa platform',
      'Contributed to microservices architecture and event-driven systems',
      'Worked with C#/.NET, Kafka, and various data stores',
    ],
    technologies: ['C# .NET', 'Kafka', 'SQL Server', 'Microservices'],
  },
  {
    id: '3',
    company: 'VORTAL',
    title: 'Software Engineer',
    startDate: '2021-08',
    endDate: '2022-04',
    location: 'Portugal',
    description: [
      'Participated in building initial microservices during transition from monolith to microservices',
      'Helped establish patterns for future services',
      'Developed backend services using C# .NET Core and SQL Server',
    ],
    technologies: ['C# .NET Core', 'SQL Server', 'Entity Framework'],
  },
  {
    id: '4',
    company: 'Closer Consulting',
    title: 'Junior Software Engineer',
    startDate: '2020-09',
    endDate: '2021-08',
    location: 'Portugal',
    description: [
      'Developed web applications using .NET MVC and Razor',
      'Worked with SQL Server for data management',
      'Contributed to various client projects',
    ],
    technologies: ['.NET MVC', 'Razor', 'SQL Server'],
  },
  {
    id: '5',
    company: 'Closer Consulting',
    title: 'Intern Software Engineer',
    startDate: '2020-06',
    endDate: '2020-09',
    location: 'Portugal',
    description: [
      'Learned .NET MVC framework and web development best practices',
      'Worked on small features and bug fixes',
      'Gained experience with SQL Server and Razor views',
    ],
    technologies: ['.NET MVC', 'Razor', 'SQL Server'],
  },
]
