import closerLogo from '../images/closer_consulting.webp'
import enhesaLogo from '../images/enhesa.webp'
import vortalLogo from '../images/vortal.webp'
import type { ExperienceItem } from './types'

export const experience: ExperienceItem[] = [
  {
    id: '1',
    company: 'Enhesa',
    title: 'Senior Software Engineer - Tech Lead',
    startDate: '2023-03',
    location: 'Lisbon, Portugal',
    description: [
      'Owned the design, maintenance, and evolution of core platform services, including Identity, User Management, Export, Document, and Home Page',
      'Removed a major bottleneck in the Identity Service token flow, cutting average latency from about 1.5 seconds to under 100 milliseconds by redesigning the flow, adding Redis caching aligned with token expiry, and introducing a circuit breaker',
      'Designed and delivered an Integrations Service that enabled configuration-driven integrations without code changes, reducing setup time from weeks to hours or days',
      'Led a cross-service effort that brought production vulnerabilities down to zero',
      'Introduced Stryker mutation testing to raise the quality bar beyond code coverage and expose weak tests with little real validation',
      'Coordinated a company-wide platform domain migration across multiple teams, covering CORS, CSP, network configuration, WAF rules, and SSO dependencies',
      'Migrated CI/CD pipelines from GoCD to Azure DevOps to standardize and automate deployments',
      'Documented the team architecture with Structurizr diagrams to improve shared understanding of service boundaries and dependencies',
      'Worked daily with international teams across multiple time zones, with English as the main working language',
    ],
    technologies: [
      'C# .NET 10',
      'Kafka',
      'Elasticsearch',
      'PostgreSQL',
      'Entity Framework',
      'Kubernetes',
      'Redis',
      'Structurizr',
    ],
    logo: enhesaLogo,
  },
  {
    id: '2',
    company: 'Enhesa',
    title: 'Software Engineer',
    startDate: '2022-05',
    endDate: '2023-03',
    location: 'Lisbon, Portugal',
    description: [
      'Built and maintained backend services for the Enhesa platform during its continued move toward microservices',
      'Contributed to event-driven systems and day-to-day service delivery across multiple components',
      'Worked primarily with C#/.NET, Kafka, and relational data stores',
    ],
    technologies: ['C# .NET', 'Kafka', 'SQL Server', 'Microservices'],
    logo: enhesaLogo,
  },
  {
    id: '3',
    company: 'VORTAL',
    title: 'Software Engineer',
    startDate: '2021-08',
    endDate: '2022-04',
    location: 'Portugal',
    description: [
      "Contributed to the early stages of VORTAL's move from a monolith toward microservices",
      'Helped establish backend patterns that later services could follow',
      'Built backend services using C# .NET Core and SQL Server',
    ],
    technologies: ['C# .NET Core', 'SQL Server', 'Entity Framework'],
    logo: vortalLogo,
  },
  {
    id: '4',
    company: 'Closer Consulting',
    title: 'Junior Software Engineer',
    startDate: '2020-09',
    endDate: '2021-08',
    location: 'Portugal',
    description: [
      'Built web features for client projects using .NET MVC and Razor',
      'Worked with SQL Server for application data and reporting needs',
      'Contributed across the delivery cycle, from implementation to bug fixing',
    ],
    technologies: ['.NET MVC', 'Razor', 'SQL Server'],
    logo: closerLogo,
  },
  {
    id: '5',
    company: 'Closer Consulting',
    title: 'Intern Software Engineer',
    startDate: '2020-06',
    endDate: '2020-09',
    location: 'Portugal',
    description: [
      'Learned .NET MVC and the fundamentals of web application development in a real team environment',
      'Supported small features and bug fixes while building confidence in C# and SQL Server',
      'Gained early experience with Razor views and day-to-day software delivery practices',
    ],
    technologies: ['.NET MVC', 'Razor', 'SQL Server'],
    logo: closerLogo,
  },
]
