// Exports the CV data by reading the live site content (single source of truth
// for facts) and merging the CV-only text from cv-data.json. Run via vite-node
// (from apps/web) so the content's image imports resolve through Vite.
//
//   pnpm -C apps/web exec vite-node scripts/cv/export-cv-data.ts
//
// Output: scripts/cv/cv-build.json (consumed by build_cv.py).
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { conferences } from '../../src/content/conferences'
import { education } from '../../src/content/education'
import { experience } from '../../src/content/experience'
import { profile } from '../../src/content/profile'
import { getExperience } from '../../src/utils/experience'
import cvData from './cv-data.json'

const here = dirname(fileURLToPath(import.meta.url))

const years = getExperience().years
const summary = cvData.summary.replace('{{years}}', `${years} years`)
const prose = cvData.experienceProse as Record<string, string[]>

const build = {
  generatedNote:
    'GENERATED by scripts/cv/export-cv-data.ts. Do not edit by hand. Edit the site content or scripts/cv/cv-data.json, then run `npm run cv`.',
  profile: {
    name: profile.name,
    role: profile.role,
    email: profile.email,
    phone: cvData.phone,
    linkedin: profile.linkedin,
    linkedinHandle: profile.linkedinHandle,
    github: profile.github,
    githubHandle: profile.githubHandle,
    location: profile.location,
  },
  summary,
  skills: cvData.skills,
  experience: experience.map((e) => ({
    company: e.company,
    title: e.title,
    startDate: e.startDate,
    endDate: e.endDate ?? null,
    location: e.location,
    technologies: e.technologies,
    prose: prose[e.id] ?? [],
  })),
  education: education.map((ed) => ({
    institution: ed.institution,
    degree: ed.degree,
    field: ed.field,
    startDate: ed.startDate,
    endDate: ed.endDate ?? null,
    location: ed.location,
    gpa: ed.gpa ?? null,
    achievements: ed.achievements ?? [],
  })),
  conferences: conferences.map((c) => ({
    name: c.name,
    type: c.type,
    date: c.date,
    location: c.location,
    description: c.description ?? null,
  })),
}

writeFileSync(join(here, 'cv-build.json'), `${JSON.stringify(build, null, 2)}\n`, 'utf8')
console.log(
  `cv-build.json written: ${build.experience.length} roles, ${build.education.length} education, ${build.conferences.length} conferences, years=${years}`,
)
